version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: tpm_bunker_mongodb
    env_file:
      - ./src/.env.docker
    command: ["mongod", "--quiet", "--logpath", "/dev/null"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27017:27017"
    healthcheck:
      test: mongosh --eval "db.adminCommand('ping')"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - internal_network

  tpm_bunker_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tpm_bunker_api
    depends_on:
      mongodb:
        condition: service_healthy
    env_file:
      - ./src/.env.docker
    ports:
      - 8003:8003
    environment:
      DEBUG: 1
      TZ: "America/Sao_Paulo"
      PGTZ: "America/Sao_Paulo"
    networks:
      - internal_network

volumes:
  mongo_data:

networks:
  internal_network:
