// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuthLogin() {
  return window['go']['main']['App']['AuthLogin']();
}

export function CheckConnection() {
  return window['go']['main']['App']['CheckConnection']();
}

export function CheckTPMPresence() {
  return window['go']['main']['App']['CheckTPMPresence']();
}

export function GetDeviceInfo() {
  return window['go']['main']['App']['GetDeviceInfo']();
}

export function GetTPMStatus() {
  return window['go']['main']['App']['GetTPMStatus']();
}

export function InitializeDevice() {
  return window['go']['main']['App']['InitializeDevice']();
}

export function IsDeviceInitialized() {
  return window['go']['main']['App']['IsDeviceInitialized']();
}
