// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecuteOperation(arg1) {
  return window['go']['main']['App']['ExecuteOperation'](arg1);
}

export function GetTPMStatus() {
  return window['go']['main']['App']['GetTPMStatus']();
}
